# Generated by Django 5.1.6 on 2025-04-12 13:38

import content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audiofiles', validators=[content.models.audio_validator])),
                ('disc', models.TextField(max_length=200)),
                ('emotion', models.CharField(choices=[('quizzes', 'quizzes'), ('stories', 'stories'), ('music', 'music'), ('comfort_videos', 'comfort_videos'), ('motivational_talks', 'motivational_talks'), ('calming_music', 'calming_music'), ('venting_games', 'venting_games'), ('stress_relief_tips', 'stress_relief_tips'), ('meditation_guides', 'meditation_guides'), ('soothing_podcasts', 'soothing_podcasts'), ('affirmations', 'affirmations'), ('interactive_tools', 'interactive_tools'), ('trending_content', 'trending_content'), ('puzzles', 'puzzles'), ('minimalist_tools', 'minimalist_tools'), ('short_reads', 'short_reads'), ('focus_timers', 'focus_timers'), ('romantic_stories', 'romantic_stories'), ('love_songs', 'love_songs'), ('couple_challenges', 'couple_challenges'), ('challenges', 'challenges'), ('goal_setting_tools', 'goal_setting_tools'), ('hype_playlists', 'hype_playlists'), ('breakup_talks', 'breakup_talks'), ('emotional_songs', 'emotional_songs'), ('relatable_stories', 'relatable_stories'), ('how_to_videos', 'how_to_videos'), ('documentaries', 'documentaries'), ('knowledge_content', 'knowledge_content')], default='happy', max_length=50)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videofiles', validators=[content.models.video_validator])),
                ('disc', models.TextField(max_length=200)),
                ('emotion', models.CharField(choices=[('quizzes', 'quizzes'), ('stories', 'stories'), ('music', 'music'), ('comfort_videos', 'comfort_videos'), ('motivational_talks', 'motivational_talks'), ('calming_music', 'calming_music'), ('venting_games', 'venting_games'), ('stress_relief_tips', 'stress_relief_tips'), ('meditation_guides', 'meditation_guides'), ('soothing_podcasts', 'soothing_podcasts'), ('affirmations', 'affirmations'), ('interactive_tools', 'interactive_tools'), ('trending_content', 'trending_content'), ('puzzles', 'puzzles'), ('minimalist_tools', 'minimalist_tools'), ('short_reads', 'short_reads'), ('focus_timers', 'focus_timers'), ('romantic_stories', 'romantic_stories'), ('love_songs', 'love_songs'), ('couple_challenges', 'couple_challenges'), ('challenges', 'challenges'), ('goal_setting_tools', 'goal_setting_tools'), ('hype_playlists', 'hype_playlists'), ('breakup_talks', 'breakup_talks'), ('emotional_songs', 'emotional_songs'), ('relatable_stories', 'relatable_stories'), ('how_to_videos', 'how_to_videos'), ('documentaries', 'documentaries'), ('knowledge_content', 'knowledge_content')], default='happy', max_length=50)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
